# Generated by Django 4.0.6 on 2022-08-02 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LCS', '0002_supplier_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ProductName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='price',
        ),
    ]
