# Generated by Django 4.0.6 on 2022-08-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCS', '0003_customer_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=40)),
                ('destination', models.CharField(max_length=40)),
            ],
        ),
    ]
