# Generated by Django 4.0.6 on 2022-08-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LCS', '0003_rename_productname_product_name_and_more'),
        ('LCS', '0004_location'),
    ]

    operations = [
    ]
