# Generated by Django 4.0.6 on 2022-08-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCS', '0008_order_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
