# Generated by Django 4.0.6 on 2022-08-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCS', '0009_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order_item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
