# Generated by Django 4.0.6 on 2022-08-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCS', '0010_remove_product_quantity_order_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
