# Generated by Django 4.0.6 on 2022-08-06 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LCS', '0012_alter_order_item_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LCS.product'),
        ),
    ]
