# Generated by Django 4.0.6 on 2022-08-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCS', '0015_alter_location_destination_alter_product_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('prod_id', models.IntegerField()),
                ('ordered_date', models.DateField(auto_now_add=True)),
                ('ordered', models.BooleanField(default=False)),
                ('vehicle_id', models.IntegerField()),
                ('source', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
